### ISSUE TITLE
2つの代名詞itがそれぞれ違うものを指しているので文を変えたほうがよさそう

### ISSUE THREAD

**Issue by kmuto** [tukaelu/sabadashi#6]
https://github.com/tukaelu/sabadashi/blob/0e87ae91bc8d46a37565005baa0f2626ad61a903/internal/subcommand/host/command.go#L41
```
export directory '%s' is already exists, so please back it up and run it again
```
最初のitはexport directory、次のitはsabadashiコマンド?

**Comment by tukaelu** [comment]
修正済みなのでクローズします。
