### ISSUE TITLE
プログレスバーが動作するたびに改行されていく

### ISSUE THREAD

**Issue by kmuto** [tukaelu/sabadashi#7]
仕様なのか判断がつかなかったのですが、プログレスバーが進捗するたびに改行されていくようです(macOS)。

**Comment by tukaelu** [comment]
自分もmac環境で再現しないので恐らくターミナル環境の問題かと思われます。（仕様ということはないです）
[schollz/progressbar](https://github.com/schollz/progressbar)を使用しているのですが、関連しそうなIssueがあるかはちょっと確認してみます。

あと念のため以下のような情報も貰えると嬉しいです。

- macOSのバージョン
- ターミナルソフトウェアの種類・バージョン
- 使用しているシェル環境

**Comment by kmuto** [comment]
- Ventura 13.6
- iTerm2 3.4.21
- /bin/zsh
となります。

**Comment by tukaelu** [comment]
@kmuto 
自分が使用している[Alacritty](https://alacritty.org/)では再現しなかったのですが、iTerm2やmacOS標準のターミナルで再現することを確認しました。
https://github.com/schollz/progressbar/issues/97 に関連していそうで、まだ未解決みたいですね。

パッチを送るより表示を調整するほうが低コストで最大限回避できそうだったので v0.1.7 で対応してみましたが、ターミナルの表示サイズに依存しそうなので最大限回避としています。ついでに表示内容もちょっとだけわかりやすく調整しております。

![スクリーンショット 2023-10-22 16 04 21](https://github.com/tukaelu/sabadashi/assets/26830736/58b055d1-dd76-4e41-bbc1-2041cab4a726)

**Comment by kmuto** [comment]
kawaii!

iTerm2, macターミナルだと改行されるのはしょうがなさそうですね。

```

🐟 Donwload host metrics (create 5 file(s))   6% [>                         ]                                                                               

🐟 Donwload host metrics (create 5 file(s))  13% [==>                       ]                                                                               

🐟 Donwload host metrics (create 5 file(s))  20% [====>                     ]                                                                               

🐟 Donwload host metrics (create 5 file(s))  26% [=====>                    ]                                                                               
 ```

**Comment by tukaelu** [comment]
@kmuto 
参考までにターミナルウィンドウごとスクショいただけると 🙏 
こちらは再現しないので解像度とか文字サイズの違いとかなのかなぁ。。

**Comment by kmuto** [comment]
キャプチャしてみました
![スクリーンショット 2023-10-23 20 27 29](https://github.com/tukaelu/sabadashi/assets/183523/2d7a873c-d5f9-4e01-9148-6cde7da9ed9f)


外付けモニタでretinaになってないですね。iTerm2 80x25文字。

**Comment by tukaelu** [comment]
@kmuto 
なるほど、横幅80（多分デフォルトかも？）だとちょっと狭いですね。。
使用しているライブラリにいくつか問題があり、次のような場合に上記が再現するようでした。

1. そもそもプログレスバーの行をクリアする処理が誤っていそう
    * https://github.com/tukaelu/sabadashi/issues/7#issuecomment-1774015437 にリンク貼ったIssue
3. リサイズしても発生する
4. 表示内容が折り返すくらい幅が狭いと発生する

上記の一部を改善するPRを本家に出しつつ、一旦幅が狭い場合でも（80くらいであれば）上記が発生しないように v0.1.8 で対応したつもりなのでご確認ください。

**Comment by kmuto** [comment]
80はたいていのターミナルでデフォルトですね…
ということで0.1.8で試したところ、横80文字でもあふれずに実行できています!
このissueはcloseいただいて構いません!
