### ISSUE TITLE
MACKEREL_APIKEY環境変数を定義してもapikeyパラメータが必須になる

### ISSUE THREAD

**Issue by kmuto** [tukaelu/sabadashi#8]
https://github.com/tukaelu/sabadashi/blob/0e87ae91bc8d46a37565005baa0f2626ad61a903/cmd/sabadashi/main.go#L38
を見るとデフォルト値として環境変数の参照をするのかな?と思ったのですが、`--apikey`を付けないと結局怒られました。

```
Required flag "apikey" not set
```

**Comment by tukaelu** [comment]
確認する限りでは再現しませんが、念のため環境変数が`MACKEREL_APIKEY`に通っているか確認していただけると。

```
echo $MACKEREL_APIKEY
sabadashi host --host <host id> --from < YYYYMMDD> --to < YYYYMMDD>
```

**Comment by kmuto** [comment]
なんかミスってたみたいで、うまく動きました! おさわがせしました
